CREATE TABLE "coworking_center" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(256) NOT NULL,
  "latitude" decimal(9,6) NOT NULL,
  "longitude" decimal(9,6) NOT NULL
);

CREATE TABLE "workspace_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(128) UNIQUE NOT NULL
);

CREATE TABLE "workspace" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coworking_center_id" int NOT NULL,
  "status_id" int NOT NULL
);

CREATE TABLE "workspace_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspace_id" int NOT NULL,
  "status_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE "reservation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspace_id" int NOT NULL,
  "customer_email" varchar(256) NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "price" money NOT NULL,
  "pricing_id" int
);

CREATE TABLE "workspace_pricing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspace_id" int NOT NULL,
  "price_per_hour" money NOT NULL,
  "valid_from" timestamp NOT NULL,
  "valid_to" timestamp
);

CREATE TABLE "user_role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(256) UNIQUE NOT NULL,
  "description" varchar(1024)
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(256) UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role_id" int NOT NULL
);

ALTER TABLE "workspace" ADD FOREIGN KEY ("coworking_center_id") REFERENCES "coworking_center" ("id");

ALTER TABLE "workspace" ADD FOREIGN KEY ("status_id") REFERENCES "workspace_status" ("id");

ALTER TABLE "workspace_history" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id");

ALTER TABLE "workspace_history" ADD FOREIGN KEY ("status_id") REFERENCES "workspace_status" ("id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("pricing_id") REFERENCES "workspace_pricing" ("id");

ALTER TABLE "workspace_pricing" ADD FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "user_role" ("id");

